[
	{"name": "Hi", "duration": 2500, "href": "main_1.html"},
	{"name": "Name", "duration": 3500, "href": "main_2.html"},
	{"name": "Legit", "duration": 3000, "href": "main_3.html"},
	{"name": "Why", "duration": 3000, "href": "main_4.html"},
	{"name": "Glad", "duration": 2500, "href": "main_5.html"},
	{"name": "Heard", "duration": 6000, "href": "main_6.html"},
	{"name": "Real", "duration": 3000, "href": "main_7.html"},
	{"name": "Done", "duration": 3000, "href": "main_8.html"},
	{"name": "About", "duration": 3000, "href": "main_9.html"},
	{"name": "Coolest", "duration": 8000, "href": "main_10.html"},
	{"name": "Won", "duration": 4000, "href": "main_10_2.html"},
	{"name": "60K", "duration": 3000, "href": "main_11.html"},
	{"name": "Education", "duration": 2500, "href": "main_12.html"},
	{"name": "Education Detail", "duration": 7000, "href": "main_13.html"},
	{"name": "Experience", "duration": 2500, "href": "main_14.html"},
	{"name": "Experience Detail 1", "duration": 8000, "href": "main_15.html"},
	{"name": "Experience Detail 2", "duration": 3000, "href": "main_15_2.html"},
	{"name": "Experience Detail 3", "duration": 8000, "href": "main_16.html"},
	{"name": "Bring", "duration": 2500, "href": "main_17.html"},
	{"name": "Bring Detail 1", "duration": 5000, "href": "main_18.html"},
	{"name": "Bring Detail 2", "duration": 5000, "href": "main_19.html"},
	{"name": "Bring Detail 3", "duration": 5000, "href": "main_20.html"},
	{"name": "What Do You Think", "duration": 3000, "href": "main_21.html"},
	{"name": "About This Resume", "duration": 3000, "href": "main_22.html"}
]